# Generated by Django 4.2.6 on 2023-11-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(max_length=100)),
                ('temperatura', models.CharField(max_length=100)),
                ('pulso', models.CharField(max_length=100)),
                ('nivel_oxigeno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('cedula_medicoatendio', models.CharField(max_length=100)),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('sintomatologia', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('duracion_tratamiento', models.CharField(max_length=100)),
                ('nombre_procedimiento', models.CharField(max_length=100)),
                ('frecuencia_repite', models.CharField(max_length=100)),
                ('numero_orden', models.CharField(max_length=100)),
                ('nombre_ayudadiagnostica', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('requiere_asistencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('nombre_emergencia', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('numero_emergencia', models.CharField(max_length=100)),
                ('nombre_compañia', models.CharField(max_length=100)),
                ('estado_poliza', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('nombrecompañia_seguro', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=100)),
                ('vigencia_poliza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_administartivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('nombre_emergencia', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('numero_emergencia', models.CharField(max_length=100)),
                ('nombre_compañia', models.CharField(max_length=100)),
                ('estado_poliza', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('nombrecompañia_seguro', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=100)),
                ('vigencia_poliza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recursosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
            ],
        ),
    ]
