# Generated by Django 4.2.6 on 2023-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_admo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('nombre_emergencia', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('numero_emergencia', models.CharField(max_length=100)),
                ('nombre_compañia', models.CharField(max_length=100)),
                ('estado_poliza', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('nombrecompañia_seguro', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=100)),
                ('vigencia_poliza', models.CharField(max_length=100)),
            ],
        ),
    ]
