# Generated by Django 4.2.6 on 2023-11-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0003_personal_admon_delete_personal_admo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('cedula_medicoatendio', models.CharField(max_length=100)),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('sintomatologia', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('numero_orden_medicamento', models.CharField(max_length=100)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('duracion_tratamiento', models.CharField(max_length=100)),
                ('numero_orden_procedimiento', models.CharField(max_length=100)),
                ('nombre_procedimiento', models.CharField(max_length=100)),
                ('cantidad_procedimiento', models.CharField(max_length=100)),
                ('frecuencia_repite', models.CharField(max_length=100)),
                ('requiere_asistencia_procedimiento', models.CharField(max_length=100)),
                ('numero_orden_ayuda', models.CharField(max_length=100)),
                ('nombre_ayudadiagnostica', models.CharField(max_length=100)),
                ('cantidad_ayuda', models.CharField(max_length=100)),
                ('requiere_asistencia_ayuda', models.CharField(max_length=100)),
            ],
        ),
    ]
