from django.db import models
from django.db.models.fields import CharField

class Recursosh(models.Model): 
    nombre = models.CharField(max_length=100)
    cedula = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    telefono = models.CharField(max_length=100)
    fecha_nacimiento = models.CharField(max_length=100)
    direccion =  models.CharField(max_length=100)
    rol = models.CharField(max_length=100)
    usuario = models.CharField(max_length=100)
    contraseña = models.CharField(max_length=100)
    licencia = models.CharField(max_length=100)
    

class Personal_administartivo(models.Model):
        nombre = models.CharField(max_length=100)
        cedula = models.CharField(max_length=100)
        ##fecha_nacimiento: models.CharField(max_length=100)
        genero = models.CharField(max_length=100)
        direccion = models.CharField(max_length=100)
       # numero_telefono: models.CharField(max_length=100)
        correo = models.CharField(max_length=100)   
        nombre_emergencia= models.CharField(max_length=100)
        relacion= models.CharField(max_length=100)

        numero_emergencia= models.CharField(max_length=100)
        nombre_compañia= models.CharField(max_length=100)
        estado_poliza= models.CharField(max_length=100)
        nombre_paciente = models.CharField(max_length=100)
        edad = models.CharField(max_length=100)
        cedula = models.CharField(max_length=100)
        nombre_medico = models.CharField(max_length=100)
        nombrecompañia_seguro = models.CharField(max_length=100)
        numero_poliza = models.CharField(max_length=100)
        vigencia_poliza = models.CharField(max_length=100)


class Personal_adm(models.Model):
        nombre = models.CharField(max_length=100)
        cedula = models.CharField(max_length=100)
        fecha_nacimiento: models.CharField(max_length=100)
        genero = models.CharField(max_length=100)
        direccion = models.CharField(max_length=100)
        numero_telefono: models.CharField(max_length=100)
        correo = models.CharField(max_length=100)   
        nombre_emergencia= models.CharField(max_length=100)
        relacion= models.CharField(max_length=100)
        numero_emergencia= models.CharField(max_length=100)
        nombre_compañia= models.CharField(max_length=100)
        estado_poliza= models.CharField(max_length=100)
        nombre_paciente = models.CharField(max_length=100)
        edad = models.CharField(max_length=100)
        cedula = models.CharField(max_length=100)
        nombre_medico = models.CharField(max_length=100)
        nombrecompañia_seguro = models.CharField(max_length=100)
        numero_poliza = models.CharField(max_length=100)
        vigencia_poliza = models.CharField(max_length=100)

class Personal_admon(models.Model):
    nombre = models.CharField(max_length=100)
    cedula = models.CharField(max_length=100)
    fecha_nacimiento= models.CharField(max_length=100)
    genero = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    numero_telefono= models.CharField(max_length=100)
    correo = models.CharField(max_length=100)   
    nombre_emergencia= models.CharField(max_length=100)
    relacion= models.CharField(max_length=100)
    numero_emergencia= models.CharField(max_length=100)
    nombre_compañia= models.CharField(max_length=100)
    estado_poliza= models.CharField(max_length=100)
    nombre_paciente = models.CharField(max_length=100)
    edad = models.CharField(max_length=100)
    cedula = models.CharField(max_length=100)
    nombre_medico = models.CharField(max_length=100)
    nombrecompañia_seguro = models.CharField(max_length=100)
    numero_poliza = models.CharField(max_length=100)
    vigencia_poliza = models.CharField(max_length=100)



class Enfermeras(models.Model):
    presion_arterial = models.CharField(max_length=100)
    temperatura = models.CharField(max_length=100)
    pulso = models.CharField(max_length=100)
    nivel_oxigeno = models.CharField(max_length=100)


class Medicos(models.Model):
    fecha = models.CharField(max_length=100)
    cedula_medicoatendio = models.CharField(max_length=100)
    motivo_consulta = models.CharField(max_length=100)
    sintomatologia = models.CharField(max_length=100)
    #diagnostico = models.CharField(max_length=100)
    numero_orden = models.CharField(max_length=100)
    nombre_medicamento = models.CharField(max_length=100)
    dosis = models.CharField(max_length=100)
    duracion_tratamiento = models.CharField(max_length=100)
    numero_orden = models.CharField(max_length=100)
    nombre_procedimiento = models.CharField(max_length=100)
    #cantidad = models.CharField(max_length=100)
    frecuencia_repite= models.CharField(max_length=100)
    requiere_asistencia = models.CharField(max_length=100)
    numero_orden = models.CharField(max_length=100)
    nombre_ayudadiagnostica = models.CharField(max_length=100)
    cantidad = models.CharField(max_length=100)
    requiere_asistencia = models.CharField(max_length=100)

class Medicos_db(models.Model):
    fecha = models.CharField(max_length=100)
    cedula_medicoatendio = models.CharField(max_length=100)
    motivo_consulta = models.CharField(max_length=100)
    sintomatologia = models.CharField(max_length=100)
    diagnostico = models.CharField(max_length=100)
    numero_orden_medicamento = models.CharField(max_length=100)
    nombre_medicamento = models.CharField(max_length=100)
    dosis = models.CharField(max_length=100)
    duracion_tratamiento = models.CharField(max_length=100)
    numero_orden_procedimiento = models.CharField(max_length=100)
    nombre_procedimiento = models.CharField(max_length=100)
    cantidad_procedimiento = models.CharField(max_length=100)
    frecuencia_repite= models.CharField(max_length=100)
    requiere_asistencia_procedimiento = models.CharField(max_length=100)
    numero_orden_ayuda = models.CharField(max_length=100)
    nombre_ayudadiagnostica = models.CharField(max_length=100)
    cantidad_ayuda = models.CharField(max_length=100)
    requiere_asistencia_ayuda = models.CharField(max_length=100)
        


        

class Personal_admistativoo(models.Model):
    nombre = models.CharField(max_length=100)
    cedula = models.CharField(max_length=100)
    fecha_nacimiento= models.CharField(max_length=100)
    genero = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    numero_telefono= models.CharField(max_length=100)
    correo = models.CharField(max_length=100)   
    nombre_emergencia= models.CharField(max_length=100)
    relacion= models.CharField(max_length=100)
    numero_emergencia= models.CharField(max_length=100)
    nombre_compañia= models.CharField(max_length=100)
    estado_poliza= models.CharField(max_length=100)
    nombre_paciente = models.CharField(max_length=100)
    edad = models.CharField(max_length=100)
    cedula = models.CharField(max_length=100)
    nombre_medico = models.CharField(max_length=100)
    nombrecompañia_seguro = models.CharField(max_length=100)
    numero_poliza = models.CharField(max_length=100)
    vigencia_poliza = models.CharField(max_length=100)
    hora_cita = models.CharField(max_length=100)
    fecha_cita = models.CharField(max_length=100)
     

class Enfermerass(models.Model):
    presion_arterial = models.CharField(max_length=100)
    temperatura = models.CharField(max_length=100)
    pulso = models.CharField(max_length=100)
    nivel_oxigeno = models.CharField(max_length=100)
    registrar_medicamento = models.CharField(max_length=100)
    hora_visita = models.CharField(max_length=100)
    fecha_visita = models.CharField(max_length=100)      